Wine/Models/ErrorViewModel.cs
using System;

namespace Wine.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Wine/Models/Varietal.cs
namespace Wine.Models
{
	public class Varietal
	{
		public int VarietalId { get; set; }
		public string VarietalName { get; set; }
		public string VarietalCharacteristics { get; set; }
	}
}

Wine/Models/WineContext.cs
using Microsoft.EntityFrameworkCore;

namespace Wine.Models
{
	public class WineContext : DbContext
	{
		public DbSet <Varietal> Varietals { get; set; }

		public WineContext(DbContextOptions options) : base(options) { }
	}
}

Wine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Wine.Models;

namespace Wine.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Wine/Controllers/VarietalsController.cs
using Microsoft.AspNetCore.Mvc;
using Wine.Models;
using System.Collections.Generic;
using System.Linq;

namespace Wine.Controllers
{
	public class VarietalsController : Controller
	{
		private readonly WineContext _db;

		public VarietalsController(WineContext db)
		{
			_db = db;
		}

		public ActionResult Index()
		{
			List<Varietal> model = _db.Varietals.ToList();
			return View(model);
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Varietal varietal)
		{
			_db.Varietals.Add(varietal);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Wine/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Wine database</h1>
    
</div>

<p>@Html.ActionLink("See all varietals", "Index", "Varietals")</p>

Wine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wine</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Wine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Wine/Views/Varietals/Create.cshtml
@{
	Layout = "_Layout";
}

@model Wine.Models.Varietal

<h4>Add a new Varietal</h4>
@using (Html.BeginForm())
{
	@Html.LabelFor(model => model.VarietalName)
	@Html.TextBoxFor(model => model.VarietalName)
	@Html.LabelFor(m => m.VarietalCharacteristics)
	@Html.TextBoxFor(m => m.VarietalCharacteristics)
	<input type="submit" value="Add new Varietal" />
}

<p>@Html.ActionLink("Show all varietals", "Index")</p>

Wine/Views/Varietals/Index.cshtml
@{
  Layout = "_Layout";
}

@using Wine.Models;
@model List<Wine.Models.Varietal>;

<h1>Varietals</h1>

@if (@Model.Count == 0)
{
  <h3>No varietals have been added yet!</h3>
} 

@foreach (Varietal varietal in Model)
{
  <li>@Html.ActionLink($"{varietal.VarietalName}", "Details", new { id = varietal.VarietalId })</li>
}

<p>@Html.ActionLink("Add new varietal", "Create")</p>